print("colors_name=" .. tostring(vim.g.colors_name))
print("loaded_comment=" .. tostring(vim.g.loaded_comment ~= nil))
print("mapleader=" .. tostring(vim.g.mapleader))
print("maplocalleader=" .. tostring(vim.g.maplocalleader))
print("loaded_nvim_treesitter=" .. tostring(vim.g.loaded_nvim_treesitter ~= nil))
print("did_load_filetypes=" .. tostring(vim.g.did_load_filetypes))
print("vscode_disabled=" .. tostring(vim.g.vscode))
print("loaded_man=" .. tostring(vim.g.loaded_man))
print("loaded_gzip=" .. tostring(vim.g.loaded_gzip))
print("loaded_tarPlugin=" .. tostring(vim.g.loaded_tarPlugin))
print("loaded_zipPlugin=" .. tostring(vim.g.loaded_zipPlugin))
print("loaded_netrwPlugin=" .. tostring(vim.g.loaded_netrwPlugin))
print("loaded_tutorModePlugin=" .. tostring(vim.g.loaded_tutorModePlugin))
print("loaded_2html_plugin=" .. tostring(vim.g.loaded_2html_plugin))
print("loaded_matchit=" .. tostring(vim.g.loaded_matchit))
print("loaded_matchparen=" .. tostring(vim.g.loaded_matchparen))
print("loaded_shada_plugin=" .. tostring(vim.g.loaded_shada_plugin))
print("loaded_remote_plugins=" .. type(vim.g.loaded_remote_plugins))
