# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" "ext4"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.extraModulePackages = [];

  # The disk layout (partitions, btrfs subvolumes and their mounts) is declared
  # in ./disko.nix, which generates the fileSystems configuration. It
  # intentionally lives outside this generated file so nixos-generate-config
  # cannot clobber it.

  # No hardware.cpu.<vendor>.updateMicrocode here: golem is a QEMU guest, so
  # microcode is the hypervisor's business, not ours.

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
