# Point kubectl at the local apiserver using the cluster-admin kubeconfig
# generated by the NixOS Kubernetes module (services.kubernetes.easyCerts).
{
  pkgs,
  lib,
  config,
  ...
}: let
  kubeconfigPath = "/etc/${config.services.kubernetes.pki.etcClusterAdminKubeconfig}";
in {
  # /etc/kubernetes/cluster-admin.kubeconfig is managed by the pki module.
  environment.sessionVariables.KUBECONFIG = kubeconfigPath;

  # A kubectl wrapper that works regardless of KUBECONFIG being set, e.g.
  # `gk get sandboxes -A`.
  environment.systemPackages = [
    (pkgs.writeShellScriptBin "gk" ''
      exec env KUBECONFIG=${kubeconfigPath} ${pkgs.kubernetes}/bin/kubectl "$@"
    '')
  ];
}
