# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    # Initialize standard ARM hardware drivers (USB, Network, etc.)
    (modulesPath + "/profiles/all-hardware.nix")
  ];

  hardware.deviceTree.enable = true;
  hardware.deviceTree.name = "rockchip/rk3566-odroid-m1s.dtb";

  boot.initrd.availableKernelModules = [ "nvme" "nvme-core" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.loader.grub.enable = false;
  boot.loader.generic-extlinux-compatible.enable = true;

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
      options = ["defaults" "size=50%" "mode=755"]; # mode=755 so only root can write to those files
    };

  fileSystems."/nix" = {
      device = "/dev/disk/by-label/NIXOS_SD";
      neededForBoot = true;
      fsType = "ext4";
  };

  # Map the nested store to the standard /nix/store
  fileSystems."/nix/store" = {
    device = "/nix/nix/store";
    fsType = "none";
    options = [ "bind" ];
    neededForBoot = true;
  };

  # Map the nested var (the DB) to the standard /nix/var
  fileSystems."/nix/var" = {
    device = "/nix/nix/var";
    fsType = "none";
    options = [ "bind" ];
    neededForBoot = true;
  };

  # CRITICAL: Bind mount the physical boot folder (now at /nix/boot)
  # to /boot so the bootloader installer can find and update it.
  fileSystems."/boot" = {
    device = "/nix/boot";
    fsType = "none";
    options = [ "bind" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.end0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
